cloud:
  aws:
    credentials:
      secret-key: 'Qv78sXNds/GJq/ClncHQmLBS3xZUY6bzVNKG2KZP'
      access-key: 'AKIAS25X7LZTJT3GZLTZ'
    region:
      static: eu-west-3
    stack:
      auto: 'false'
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 5MB
      enabled: 'true'
      max-request-size: 10MB
      file-size-threshold: 2MB
  datasource:
    password: Access/fedora/6
    username: postgres
    url: jdbc:postgresql://db:5432/postgres
    driver-class-name: org.postgresql.Driver
application:
  bucket:
    name: moood-app