version: "3"

services:
  database:
    image: postgres
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: Access/db/2
    volumes:
      - psql:/var/lib/postgres/psql
    networks:
      - net
  app_service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - net
volumes:
  psql:
networks:
  net: